<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GhostFTP.Linux</RootNamespace>
    <AssemblyName>GhostFTP</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GhostFTP.Core\GhostFTP.Core.csproj" />
    <ProjectReference Include="..\GhostFTP.Design\GhostFTP.Design.csproj" />
  </ItemGroup>
</Project>
